version: "3.3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/postgresql/data
  app_server:
    depends_on:
      - db
    image: application_server
    build:
      context: server
      dockerfile: dockerfile
    #volumes:
    #  - .:/server
    restart: always
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 8080:8080
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

  mobile_service:
    build: mobile
    #  context: mobile
    #  dockerfile: dockerfile
    #image: mobile
    environment:
      MOBILE_APP_FILEPATH: /app/client/area_mobile.apk
    volumes:
      - client:/app/client
    restart: always
  
  web_service:
    depends_on:
      - app_server
      - mobile_service
    image: web
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - client:/usr/share/nginx/html/assets/client
    restart: always
    ports:
      - '8081:8081'
volumes:
  my-db:
    driver: local
  client: null
  