version: "3"
services:
  app_server:
    image: application_server
    build: .
    volumes:
      - ./server
    ports:
      -8080:8080
    restart: always
  
  mobile_service:
    depends_on:
      - app_server
    image: mobile
    volumes:
      -./mobile
    restart: always
  
  web_service:
    depends_on:
      - app_server
    image: web
    volumes:
      -./web
    restart: always