dependencies:
  http: ^0.13.5
  http_parser: 4.0.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  draggable_home: ^1.0.2
  url_launcher: ^6.1.6
  google_sign_in: ^5.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.18.1 <3.0.0'
flutter:
  assets:
    - assets/
    - .env
  uses-material-design: true
name: mobil
publish_to: none
version: 1.0.0+1