database:
  user:
  password:
  address:
  port:
  protocol:
  name:
  ParseTime:

server:
  address:

environment:
  - jwt_secret:
  - salt:
  - google_client_id:
  - google_client_secret:
  # - database_url: