FROM golang:1.19-buster as builder
WORKDIR /server/

#download necessary GO modules
COPY go.mod ./
COPY go.sum ./

RUN go mod tidy
COPY *.go ./
ADD . .

RUN go build -v -o /server/main

FROM scratch
WORKDIR /server
COPY --from=builder /server/main /server/main

EXPOSE 8081

CMD [ "/server/main" ]