FROM golang:1.19-buster as builder
WORKDIR /server

#download necessary GO modules
COPY go.mod ./
COPY go.sum ./

RUN go mod tidy
COPY *.go ./

RUN go build -v -o app-server main.go

FROM scratch
WORKDIR /server
COPY --from=builder /server/app-server /server/app-server

EXPOSE 8081

CMD [ "./server" ]