name: Build & Deploy
on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy Go app
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            session="area-server"

            tmux kill-session -t $session
            tmux new-session -d -s $session -c /root/AREA/server

            window=0
            tmux new-window -t $session:$window -n 'fetch' -c /root/AREA/server
            tmux send-keys -t $session:$window 'git fetch --prune --all'

            window=1
            tmux new-window -t $session:$window -n 'build' -c /root/AREA/server
            tmux send-keys -t $session:$window 'make build'

            window=2
            tmux new-window -t $session:$window -n 'start' -c /root/AREA/server
            tmux send-keys -t $session:$window './server'
